version: "3.9"

services:
  api:
    build: ./backend
    container_name: reminder_api
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./logs:/logs
    depends_on:
      - mongo
    env_file:
      - ./backend/.env
    environment:
      ENVIRONMENT: dev
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  mongo:
    image: mongo:7
    container_name: reminder_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
